### ISSUE TITLE
Unable to download weights

### ISSUE THREAD

**Issue by daidaiershidi** [gstoica27/KnOTS#1] opened 2024-10-28 09:32 UTC
![image](https://github.com/user-attachments/assets/fb84646d-4bad-481b-bd01-ff8f284a8687)

Thank you for the work. But when I try to download the checkpoints, I don't seem to have permission. How should I get the checkpoints?

**Comment by pratikramesh1** [comment] 2024-10-28 15:09
Can you try it again, we've updated the one-drive link, 
Thanks for checking out our work, I apologize for the inconvenience.

**Comment by daidaiershidi** [comment] 2024-10-29 15:12
Thanks for replying and sharing. But I found that llama is too big to allow downloading.
The exact download is similar to

rte.pt_Error.txt
The file size exceeds the allowed limit. 
CorrelationId: db76103b-3a16-47c2-8a6b-d2d14d1150fa, 
UTC DateTime: 10/29/2024 15:07:16

**Comment by pratikramesh1** [comment] 2024-10-31 15:43
Hi Thanks for reaching out, can you share details on how you are downloading these files? Are you using any package/tool or downloading them manually? We have tested that the latter works but can also try testing with other packages.

**Comment by daidaiershidi** [comment] 2024-11-02 03:56
> Hi Thanks for reaching out, can you share details on how you are downloading these files? Are you using any package/tool or downloading them manually? We have tested that the latter works but can also try testing with other packages.

just download by google browser. And if I download rte.pt, I will get a file named rte.pt_Error.txt. The context is The file size exceeds the allowed limit.
CorrelationId: db76103b-3a16-47c2-8a6b-d2d14d1150fa,
UTC DateTime: 10/29/2024 15:07:16

Please what should I use to download. Also I found out how to run the eval code directly, it seems that I need the head.pt and shuffle_idx files as well, how should I generate these files please?

**Comment by gstoica27** [comment] 2024-11-02 04:07
Regarding shuffle indexes, thanks for pointing this out. These are now pushed to the code base. "parsing/generate_clip_heads.py" is under the dataset directory.

**Comment by gstoica27** [comment] 2024-11-02 04:13
@pratikramesh1 knows more about the model checkpoint storage, but if this issue persists we will either move them to google drive or Hugging Face. We're sorry about this issue!

**Comment by pratikramesh1** [comment] 2024-11-04 02:53
Re downloading llama model checkpoints: Thanks for raising this issue. I was unable to reproduce the error on my device but the downloading did fail when I tried on a different device. A better solution as you suggested would be to push the weights to HuggingFace. We will do it in the next couple of days and post an update once its done.

Re heads.pt : You can find this file in the same one-drive link under the Llama-3-8B folder called "heads.pt".

**Comment by arghavan-kpm** [comment] 2024-11-06 02:00
Hi, I also got error downloading model checkpoints. Would you open link sharing access so that we can download with wget?

**Comment by pratikramesh1** [comment] 2024-11-09 08:20
The model checkpoints have been pushed to HuggingFace [here](https://huggingface.co/collections/hoffman-lab/knots-model-merging-with-svd-672d3b5fabf766c22989e760), we have also added support to pass either the huggingface model id or the local path to the model ckpt stored as a ".pt" file, hope this helps.

**Comment by gstoica27** [comment] 2024-11-11 00:15
Hi all, we'll be closing this issue for now as we've moved the location our models live to Hugging Face. Please feel free to comment/re open if you run into any issues!

**Closed** 2024-11-11 00:16 UTC
